// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppHome: typeof import('./theme/components/AppHome.vue')['default']
    HomeFeatures: typeof import('./theme/components/HomeFeatures.vue')['default']
    HomeFooter: typeof import('./theme/components/HomeFooter.vue')['default']
    HomeHero: typeof import('./theme/components/HomeHero.vue')['default']
    'IconCarbon:arrowRight': typeof import('~icons/carbon/arrow-right')['default']
    IconCarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
  }
}

export { }
